---
kind: pipeline
type: docker
name: default

steps:
- name: configure
  image: utdemir/ghc-musl:v4-integer-simple-ghc881
  environment:
    CABAL_DIR: /cabal
  volumes:
  - name: cabal-cache
    path: /cabal
  commands:
  - cabal v2-update
  - cabal v2-configure --jobs \$ncpus --enable-tests --flags +fatal-warnings

- &default-steps
  name: ghc 8.8.1
  image: utdemir/ghc-musl:v4-integer-simple-ghc881
  depends_on: [configure]
  environment:
    CABAL_DIR: /cabal
  volumes:
  - name: cabal-cache
    path: /cabal
  commands:
  - cabal v2-build
  - cabal v2-test

- <<: *default-steps
  name: ghc 8.6.5
  image: utdemir/ghc-musl:v4-integer-simple-ghc865

- <<: *default-steps
  name: ghc 8.4.4
  image: utdemir/ghc-musl:v4-libgmp-ghc844

- name: docs
  image: utdemir/ghc-musl:v4-integer-simple-ghc881
  depends_on: 
  - ghc 8.8.1
  environment:
    CABAL_DIR: /cabal
  volumes:
  - name: cabal-cache
    path: /cabal
  commands:
  - ./scripts/documentation-coverage

- name: release
  image: utdemir/ghc-musl:v4-integer-simple-ghc881
  depends_on:
  - ghc 8.8.1
  - ghc 8.6.5
  - ghc 8.4.4
  - docs
  environment:
    CABAL_DIR: /cabal
    HACKAGE_USER: {"from_secret": "hackage-user"}
    HACKAGE_PASSWORD: {"from_secret": "hackage-password"}
  volumes:
  - name: cabal-cache
    path: /cabal
  commands:
  - ./scripts/release
  when:
    event: 
    - tag

volumes:
  - name: cabal-cache
    host:
      path: /var/cache/cabal
---
kind: signature
hmac: bac8c74fe1e90b09b1882056f198fc4294c7cc72d3a875f0e0aa29b67b2e0e77

...
