#!/bin/bash
# code: language=sh
set -e

tmpfile="$(mktemp)"
trap "rm -f $tmpfile" EXIT
cabal v2-haddock --enable-documentation 2>&1 | tee "$tmpfile"
if grep --quiet --fixed-strings 'Missing documentation for:' "$tmpfile"
then
    printf -- '-----\nERROR: Not all public exports have documentation.' >&2
    exit 1
fi