#!/bin/bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

version="$(grep '^version:' prosidy.cabal | sed 's|^version: *||')"
echo "Publishing v${version}" >&2

do-upload ()
{
    cabal upload --username="${HACKAGE_USER}" --password="${HACKAGE_PASSWORD}" "$@"
}

cabal sdist
do-upload "dist-newstyle/sdist/prosidy-${version}.tar.gz"
do-upload --documentation "dist-newstyle/prosidy-${version}-docs.tar.gz"