#!/bin/bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

version="$(grep '^version:' prosidy.cabal | sed 's|^version: *||')"
echo "Publishing v${version}" >&2

cabal sdist
cabal upload --username="${HACKAGE_USER}" --password="${HACKAGE_PASSWORD}" "dist-newstyle/sdist/prosidy-${version}.tar.gz"
cabal upload --username="${HACKAGE_USER}" --password="${HACKAGE_PASSWORD}" --documentation