on: [push, pull_request]

name: Test

jobs:

  build:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ghc:
          - '9.0'
          - '8.10'
          - '8.8'
          - '8.6'

    steps:
      - uses: actions/checkout@v2

      - name: Cache Haskell dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
          key: ${{ runner.os }}-${{ matrix.ghc }}

      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Test
        run: runhaskell --ghc-arg='-package process' ./.github/workflows/test.hs
        env:
          ghc: ${{ matrix.ghc }}
